[package]
name = "subscription_with_channel"
version = "0.1.0"
authors = ["dearkarm"]
edition = "2018"

[dependencies]
iced = { path = "../../", features = ["tokio"] }
iced_native = { path = "../../native" }
iced_futures = { path = "../../futures" }
tokio = { version = "1", features = ["sync"] }
