[package]
name = "iced_winit"
version = "0.1.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = ["iced_native/debug"]

[dependencies]
log = "0.4"

[dependencies.iced_native]
version = "0.2"
path = "../native"

[dependencies.iced_graphics]
version = "0.1"
path = "../graphics"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
window_clipboard = "0.1"
winit = "0.22"

[target.'cfg(target_arch = "wasm32")'.dependencies.winit]
version = "0.22"
default_features = false
features = ["web-sys"]
